name: build

on: 
  push:            # run on push events
    paths-ignore:  # but ignore everything in the docs subfolder 
      - 'docs/**'
    tags:
      - '*'
  pull_request:    # run on pull requests
    paths-ignore:  # but ignore everything in the docs subfolder 
      - 'docs/**'

jobs:
  publish-wheels:
    runs-on: ubuntu-latest

    steps:
    - name: Cloning SUMO
      uses: actions/checkout@v2
      with:
        path: sumo

    - name: Fetching tags, building wheel
      run: |
        cd sumo
        git fetch --prune --unshallow
        python tools/build/setup-sumolib.py bdist_wheel

    - name: Publish to Test PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.TEST_PYPI_TOKEN }}
        repository_url: https://test.pypi.org/legacy/
