name: linux-wheels

on:
  push:            # run on push events
    branches:
      - '**'
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build-manylinux-wheels:
    runs-on: ubuntu-24.04

    steps:
    - name: Cloning SUMO
      uses: actions/checkout@v4
      with:
        path: sumo0

    - name: Check version
      run: cd sumo0 && git describe

    - name: Cloning SUMO with tags
      uses: actions/checkout@v4
      with:
        fetch-tags: true
        path: sumo1

    - name: Check version
      run: cd sumo1 && git describe

    - name: Cloning SUMO with depth 0
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        path: sumo2

    - name: Check version
      run: cd sumo2 && git describe

    - name: Cloning SUMO with depth 0 and tree filter
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        filter: tree:0
        path: sumo3

    - name: Check version
      run: cd sumo3 && git describe

    - name: Cloning SUMO with depth 0 and tree filter and tags
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        filter: tree:0
        fetch-tags: true
        path: sumo4

    - name: Check version
      run: cd sumo4 && git describe
