name: windows-wheels

on:
  push:            # run on push events
    paths-ignore:  # but ignore everything in the docs subfolder
      - 'docs/**'
      - 'src/gui*/**'
      - 'src/netedit/**'
      - 'tests/netedit/**'
    branches:
      - '**'
    tags:
      - '*'
  pull_request:    # run on pull requests
    paths-ignore:  # but ignore everything in the docs subfolder
      - 'docs/**'
  workflow_dispatch:
  schedule:
    - cron:  '5 1 * * *'

jobs:
  test-deps:
    runs-on: windows-latest

    steps:
    - name: Testing dependency checker
      run: |
          Invoke-WebRequest -Uri https://github.com/lucasg/Dependencies/releases/download/v1.11.1/Dependencies_x64_Release_.without.peview.exe.zip -OutFile Dependencies.zip
          7z x -oDependencies Dependencies.zip
          Dependencies\Dependencies.exe -help

    - name: Installing libsumo
      run: |
        python -m pip install libsumo
        python -c "import libsumo; print(libsumo.__file__)"
        python -c "import libsumo, subprocess; subprocess.call(['Dependencies\Dependencies.exe', '-modules', '-depth', '2', libsumo.__file__.replace('__init__.py', '_libsumo.pyd')])"
